### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [Hong-sohyeon/C202309#2]
### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week6/studentGrade
    - Error: use of undeclared identifier 'average' [line 46]
        - average 변수가 선언되지 않았습니다. 변수를 선언한 후 사용해주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/studentGrade
    - Warning: implicit declaration of function 'printRanks' is invalid in C99 [line 82]
       - printRanks 함수가 없습니다. 함수를 만들어주세요.

**Comment by Hong-sohyeon** [comment]
해결했다는 코멘트 달지 않아서 추가합니다!
